spring.application.name=Help

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?sslmode=prefer
spring.datasource.username=postgres
spring.datasource.password=tecamini
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=10000
spring.jpa.show-sql=true 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.format_sql=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=suportesistemahelp@gmail.com
spring.mail.password=idfvzeqjmhikplss
api.security.token.secret=${JWT_SECRET:minha-chave-secreta-32-caracteres}
logging.level.org.springframework.security=DEBUG
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true