spring.application.name=Help

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?sslmode=prefer
spring.datasource.username=postgres
spring.datasource.password=tecamini
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=10000
spring.jpa.show-sql=true 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.format_sql=true